"""
Story Export - Save stories to various formats.

Export generated stories to Markdown, HTML, JSON, and plain text.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import Optional, Union

from samuel_clemens.stories.generator import GeneratedStory
from samuel_clemens.stories.recombinator import RecombinedStory
from samuel_clemens.utils.logging import story_log


def export_to_markdown(
    story: Union[GeneratedStory, RecombinedStory],
    filepath: Optional[Path] = None,
    include_metadata: bool = True,
) -> str:
    """
    Export a story to Markdown format.
    
    Args:
        story: Story to export
        filepath: Optional path to save to
        include_metadata: Include generation metadata
        
    Returns:
        Markdown string
    """
    lines = []
    
    # Title
    lines.append(f"# {story.title}")
    lines.append("")
    
    # Story text
    lines.append(story.text)
    lines.append("")
    
    # Metadata
    if include_metadata:
        lines.append("---")
        lines.append("")
        lines.append("## Story Metadata")
        lines.append("")
        lines.append(f"- **Word Count**: {story.word_count}")
        
        if isinstance(story, GeneratedStory):
            lines.append(f"- **Template**: {story.template_used}")
            lines.append(f"- **Emotion**: {story.emotion.value}")
            if story.character:
                lines.append(f"- **Character**: {story.character.name}")
            if story.setting:
                lines.append(f"- **Setting**: {story.setting.name}")
            if story.theme:
                lines.append(f"- **Theme**: {story.theme.name}")
        elif isinstance(story, RecombinedStory):
            lines.append(f"- **Mashup Type**: {story.mashup_type}")
            if story.source_stories:
                lines.append(f"- **Sources**: {', '.join(story.source_stories)}")
        
        lines.append(f"- **Generated**: {datetime.now().isoformat()}")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by Samuel Clemens - MarkTwainVerse*")
    
    content = "\n".join(lines)
    
    if filepath:
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(content)
        story_log(f"📝 Exported story to {filepath}")
    
    return content


def export_to_html(
    story: Union[GeneratedStory, RecombinedStory],
    filepath: Optional[Path] = None,
    include_styles: bool = True,
) -> str:
    """
    Export a story to HTML format.
    
    Args:
        story: Story to export
        filepath: Optional path to save to
        include_styles: Include inline CSS styles
        
    Returns:
        HTML string
    """
    styles = """
    <style>
        body {
            font-family: 'Georgia', serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            background: #f9f7f1;
            color: #333;
        }
        h1 {
            font-size: 2.5em;
            border-bottom: 2px solid #8b4513;
            padding-bottom: 10px;
            color: #8b4513;
        }
        .story-text {
            font-size: 1.2em;
            line-height: 1.8;
            text-align: justify;
        }
        .metadata {
            margin-top: 30px;
            padding: 20px;
            background: #fff;
            border-left: 4px solid #8b4513;
        }
        .metadata h2 {
            color: #8b4513;
            margin-top: 0;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #888;
            font-style: italic;
        }
    </style>
    """ if include_styles else ""
    
    # Build metadata section
    metadata_items = [f"<li><strong>Word Count</strong>: {story.word_count}</li>"]
    
    if isinstance(story, GeneratedStory):
        metadata_items.append(f"<li><strong>Template</strong>: {story.template_used}</li>")
        metadata_items.append(f"<li><strong>Emotion</strong>: {story.emotion.value}</li>")
        if story.character:
            metadata_items.append(f"<li><strong>Character</strong>: {story.character.name}</li>")
        if story.setting:
            metadata_items.append(f"<li><strong>Setting</strong>: {story.setting.name}</li>")
    elif isinstance(story, RecombinedStory):
        metadata_items.append(f"<li><strong>Mashup Type</strong>: {story.mashup_type}</li>")
        if story.source_stories:
            metadata_items.append(f"<li><strong>Sources</strong>: {', '.join(story.source_stories)}</li>")
    
    metadata_items.append(f"<li><strong>Generated</strong>: {datetime.now().strftime('%Y-%m-%d %H:%M')}</li>")
    
    # Escape HTML in story text and convert newlines
    story_html = story.text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    story_html = story_html.replace("\n\n", "</p><p>").replace("\n", "<br>")
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{story.title}</title>
    {styles}
</head>
<body>
    <h1>🎩 {story.title}</h1>
    
    <div class="story-text">
        <p>{story_html}</p>
    </div>
    
    <div class="metadata">
        <h2>Story Details</h2>
        <ul>
            {''.join(metadata_items)}
        </ul>
    </div>
    
    <div class="footer">
        <p>Generated by Samuel Clemens - MarkTwainVerse</p>
    </div>
</body>
</html>
"""
    
    if filepath:
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(html)
        story_log(f"🌐 Exported story to {filepath}")
    
    return html


def export_to_json(
    story: Union[GeneratedStory, RecombinedStory],
    filepath: Optional[Path] = None,
) -> str:
    """
    Export a story to JSON format.
    
    Args:
        story: Story to export
        filepath: Optional path to save to
        
    Returns:
        JSON string
    """
    data = {
        "title": story.title,
        "text": story.text,
        "word_count": story.word_count,
        "generated_at": datetime.now().isoformat(),
        "generator": "samuel_clemens",
        "version": "0.2.0",
    }
    
    if isinstance(story, GeneratedStory):
        data["type"] = "generated"
        data["template"] = story.template_used
        data["emotion"] = story.emotion.value
        if story.character:
            data["character"] = {
                "name": story.character.name,
                "role": story.character.role,
                "traits": story.character.traits,
            }
        if story.setting:
            data["setting"] = {
                "name": story.setting.name,
                "atmosphere": story.setting.atmosphere,
            }
        if story.theme:
            data["theme"] = {
                "name": story.theme.name,
            }
    elif isinstance(story, RecombinedStory):
        data["type"] = "recombined"
        data["mashup_type"] = story.mashup_type
        data["source_stories"] = story.source_stories
        # Serialize blended_elements to strings
        data["blended_elements"] = [
            el.name if hasattr(el, 'name') else str(el) 
            for el in story.blended_elements
        ] if story.blended_elements else []
    
    json_str = json.dumps(data, indent=2)
    
    if filepath:
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(json_str)
        story_log(f"📦 Exported story to {filepath}")
    
    return json_str


def export_to_text(
    story: Union[GeneratedStory, RecombinedStory],
    filepath: Optional[Path] = None,
) -> str:
    """
    Export a story to plain text format.
    
    Args:
        story: Story to export
        filepath: Optional path to save to
        
    Returns:
        Plain text string
    """
    lines = []
    lines.append("=" * 60)
    lines.append(story.title.center(60))
    lines.append("=" * 60)
    lines.append("")
    lines.append(story.text)
    lines.append("")
    lines.append("-" * 60)
    lines.append(f"Words: {story.word_count}")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("-" * 60)
    
    content = "\n".join(lines)
    
    if filepath:
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(content)
        story_log(f"📄 Exported story to {filepath}")
    
    return content


def export_story(
    story: Union[GeneratedStory, RecombinedStory],
    filepath: Path,
    format: str = "auto",
) -> str:
    """
    Export a story, auto-detecting format from file extension.
    
    Args:
        story: Story to export
        filepath: Path to save to
        format: Format (auto, markdown, html, json, text)
        
    Returns:
        Exported content string
    """
    filepath = Path(filepath)
    
    # Auto-detect format
    if format == "auto":
        ext = filepath.suffix.lower()
        format_map = {
            ".md": "markdown",
            ".markdown": "markdown",
            ".html": "html",
            ".htm": "html",
            ".json": "json",
            ".txt": "text",
        }
        format = format_map.get(ext, "markdown")
    
    # Export
    if format == "markdown":
        return export_to_markdown(story, filepath)
    elif format == "html":
        return export_to_html(story, filepath)
    elif format == "json":
        return export_to_json(story, filepath)
    elif format == "text":
        return export_to_text(story, filepath)
    else:
        return export_to_markdown(story, filepath)


def export_anthology(
    stories: list[Union[GeneratedStory, RecombinedStory]],
    directory: Path,
    format: str = "markdown",
    create_index: bool = True,
) -> list[Path]:
    """
    Export a collection of stories to a directory.
    
    Args:
        stories: List of stories to export
        directory: Directory to save to
        format: Export format
        create_index: Create an index file
        
    Returns:
        List of created file paths
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    
    ext_map = {
        "markdown": ".md",
        "html": ".html",
        "json": ".json",
        "text": ".txt",
    }
    ext = ext_map.get(format, ".md")
    
    created_files = []
    
    for i, story in enumerate(stories, 1):
        # Create safe filename
        safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in story.title)
        safe_title = safe_title.replace(" ", "_")[:50]
        filename = f"{i:02d}_{safe_title}{ext}"
        
        filepath = directory / filename
        export_story(story, filepath, format)
        created_files.append(filepath)
    
    # Create index
    if create_index:
        index_path = directory / f"index{ext}"
        
        if format == "markdown":
            index_lines = ["# Story Anthology", "", f"Generated: {datetime.now().isoformat()}", ""]
            for i, story in enumerate(stories, 1):
                safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in story.title)
                safe_title = safe_title.replace(" ", "_")[:50]
                index_lines.append(f"{i}. [{story.title}]({i:02d}_{safe_title}{ext})")
            index_path.write_text("\n".join(index_lines))
            created_files.append(index_path)
        elif format == "html":
            index_html = f"""<!DOCTYPE html>
<html><head><title>Story Anthology</title></head>
<body>
<h1>Story Anthology</h1>
<p>Generated: {datetime.now().isoformat()}</p>
<ul>
"""
            for i, story in enumerate(stories, 1):
                safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in story.title)
                safe_title = safe_title.replace(" ", "_")[:50]
                index_html += f'<li><a href="{i:02d}_{safe_title}{ext}">{story.title}</a></li>\n'
            index_html += "</ul></body></html>"
            index_path.write_text(index_html)
            created_files.append(index_path)
        else:
            # For json and text, skip index (or implement if needed)
            pass
        
        story_log(f"📚 Exported anthology with {len(stories)} stories to {directory}")
    
    return created_files
